# Generated by Django 6.0.3 on 2026-03-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_demand', models.IntegerField()),
                ('forecast_month', models.CharField(max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
