# Generated by Django 6.0.3 on 2026-03-08 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_initial'),
        ('services', '0004_alter_servicetype_options_demandforecast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandforecast',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_demands', to='services.servicetype'),
        ),
    ]
