# Generated by Django 6.0.3 on 2026-03-08 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        ('services', '0004_alter_servicetype_options_demandforecast_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('variables', models.JSONField(default=list, help_text="e.g., ['technician_name', 'service_type']")),
            ],
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='services.servicerequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='send_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='services.serviceticket'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ticket_assigned', 'Ticket Assigned'), ('status_update', 'Status Update'), ('reminder', 'Reminder'), ('urgent', 'Urgent Alert'), ('task_completed', 'Task Completed'), ('customer_inquiry', 'Customer Inquiry'), ('message', 'New Message')], default='message', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_status', models.CharField(default='pending', max_length=50)),
                ('sms_status', models.CharField(default='pending', max_length=50)),
                ('email_response', models.TextField(blank=True, null=True)),
                ('sms_response', models.TextField(blank=True, null=True)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='notifications.notification')),
            ],
        ),
    ]
