# Generated by Django 6.0.3 on 2026-03-17 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationtemplate_alter_notification_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ticket_assigned', 'Ticket Assigned'), ('status_update', 'Status Update'), ('reminder', 'Reminder'), ('urgent', 'Urgent Alert'), ('task_completed', 'Task Completed'), ('customer_inquiry', 'Customer Inquiry'), ('message', 'New Message'), ('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='message', max_length=50),
        ),
        migrations.CreateModel(
            name='FirebaseToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.TextField(unique=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(choices=[('web', 'Web'), ('ios', 'iOS'), ('android', 'Android')], default='web', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firebase_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_1bb9fb_idx')],
            },
        ),
    ]
