# Generated by Django 6.0.3 on 2026-03-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateTimeField()),
                ('service_duration', models.IntegerField(help_text='Duration in minutes')),
                ('customer_rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
