# Generated by Django 6.0.3 on 2026-03-06 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0002_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicehistory',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'role': 'technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicehistory',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='services.serviceticket'),
        ),
    ]
