# Generated by Django 6.0.3 on 2026-03-06 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicelocation',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='services.servicerequest'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicerequest'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'role': 'technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetype'),
        ),
        migrations.AddField(
            model_name='technicianskill',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetype'),
        ),
        migrations.AddField(
            model_name='technicianskill',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
