# Generated by Django 6.0.3 on 2026-03-08 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicerequest_auto_ticket_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('forecast_period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('predicted_requests', models.IntegerField()),
                ('confidence_level', models.FloatField(default=0.8)),
                ('weather_impact', models.FloatField(default=0)),
                ('seasonal_trend', models.FloatField(default=0)),
                ('historical_average', models.IntegerField(default=0)),
                ('actual_requests', models.IntegerField(blank=True, null=True)),
                ('forecast_accuracy', models.FloatField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_demands', to='services.servicetype')),
            ],
            options={
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[('seasonal', 'Seasonal'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('average_requests', models.FloatField()),
                ('peak_day', models.CharField(blank=True, max_length=20)),
                ('peak_hour', models.IntegerField(blank=True, null=True)),
                ('growth_rate', models.FloatField(default=0)),
                ('trend_direction', models.CharField(default='stable', max_length=20)),
                ('standard_deviation', models.FloatField(default=0)),
                ('confidence_interval', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_requests', models.IntegerField(default=0)),
                ('completed_requests', models.IntegerField(default=0)),
                ('pending_requests', models.IntegerField(default=0)),
                ('cancelled_requests', models.IntegerField(default=0)),
                ('avg_response_time_hours', models.FloatField(default=0)),
                ('avg_completion_time_hours', models.FloatField(default=0)),
                ('technician_utilization_rate', models.FloatField(default=0)),
                ('service_area_coverage', models.FloatField(default=0)),
                ('popular_locations', models.JSONField(default=list)),
                ('satisfaction_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicetype')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'service_type')},
            },
        ),
        migrations.CreateModel(
            name='TechnicianPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tickets_assigned', models.IntegerField(default=0)),
                ('tickets_completed', models.IntegerField(default=0)),
                ('tickets_pending', models.IntegerField(default=0)),
                ('total_work_hours', models.FloatField(default=0)),
                ('avg_response_time_hours', models.FloatField(default=0)),
                ('avg_completion_time_hours', models.FloatField(default=0)),
                ('customer_satisfaction', models.FloatField(default=0)),
                ('rework_rate', models.FloatField(default=0)),
                ('distance_traveled_km', models.FloatField(default=0)),
                ('fuel_efficiency', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('technician', 'date')},
            },
        ),
    ]
