# Generated by Django 4.2.29 on 2026-03-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_servicetype_options_demandforecast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='client_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='client_rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
