# Generated by Django 6.0.3 on 2026-03-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceticket_client_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='route_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='route_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='route_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
