# Generated by Django 6.0.3 on 2026-03-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_serviceticket_route_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Not Started', max_length=50),
        ),
    ]
