# Generated by Django 4.2.29 on 2026-03-19 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0007_serviceticket_created_at_serviceticket_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSalesCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('follow_up', 'Follow Up'), ('complaint', 'Complaint'), ('warranty', 'Warranty'), ('revisit', 'Revisit'), ('feedback', 'Feedback')], default='follow_up', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('requires_revisit', models.BooleanField(default=False)),
                ('customer_satisfaction', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'after_sales'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_after_sales_cases', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='after_sales_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_after_sales_cases', to=settings.AUTH_USER_MODEL)),
                ('service_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_sales_cases', to='services.serviceticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
