# Generated by Django 4.2.29 on 2026-03-19 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0008_aftersalescase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftersalescase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'follow_up'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_after_sales_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
