# Generated by Django 6.0.3 on 2026-03-19 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_aftersalescase_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionchecklist',
            name='maintenance_interval_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='maintenance_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='maintenance_profile',
            field=models.CharField(blank=True, choices=[('commercial_area', 'Commercial Area'), ('dust_free_area', 'Dust-Free Area'), ('standard_area', 'Standard Area')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='maintenance_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aftersalescase',
            name='case_type',
            field=models.CharField(choices=[('follow_up', 'Follow Up'), ('maintenance', 'Maintenance'), ('complaint', 'Complaint'), ('warranty', 'Warranty'), ('revisit', 'Revisit'), ('feedback', 'Feedback')], default='follow_up', max_length=20),
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_profile', models.CharField(choices=[('commercial_area', 'Commercial Area'), ('dust_free_area', 'Dust-Free Area'), ('standard_area', 'Standard Area')], max_length=30)),
                ('interval_days', models.PositiveIntegerField()),
                ('follow_up_window_days', models.PositiveIntegerField(default=14)),
                ('last_service_date', models.DateField()),
                ('next_due_date', models.DateField()),
                ('notify_on_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('due_soon', 'Due Soon'), ('due', 'Due'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], default='scheduled', max_length=20)),
                ('maintenance_notes', models.TextField(blank=True, null=True)),
                ('due_soon_notified_at', models.DateTimeField(blank=True, null=True)),
                ('due_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to=settings.AUTH_USER_MODEL)),
                ('service_ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedule', to='services.serviceticket')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='services.servicetype')),
            ],
            options={
                'ordering': ['next_due_date', 'id'],
            },
        ),
    ]
