# Generated by Django 6.0.3 on 2026-03-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_inspectionchecklist_maintenance_interval_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionchecklist',
            name='proof_media',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='warranty_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='warranty_period_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='warranty_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='prediction_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='risk_level',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='risk_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_time_slot',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (8 AM - 11 AM)'), ('midday', 'Midday (11 AM - 2 PM)'), ('afternoon', 'Afternoon (2 PM - 5 PM)'), ('evening', 'Evening (5 PM - 8 PM)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='scheduling_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='reschedule_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='reschedule_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='reschedule_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='scheduled_time_slot',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (8 AM - 11 AM)'), ('midday', 'Midday (11 AM - 2 PM)'), ('afternoon', 'Afternoon (2 PM - 5 PM)'), ('evening', 'Evening (5 PM - 8 PM)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='smart_assignment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='smart_assignment_summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='warranty_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='warranty_period_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='warranty_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('active', 'Active'), ('expired', 'Expired'), ('void', 'Void')], default='not_applicable', max_length=20),
        ),
    ]
