# Generated by Django 6.0.3 on 2026-03-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_inspectionchecklist_proof_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aftersalescase',
            name='creation_source',
            field=models.CharField(
                choices=[
                    ('manual', 'Manual'),
                    ('completion_flow', 'Completion Flow'),
                    ('maintenance_alert', 'Maintenance Alert'),
                ],
                default='manual',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='follow_up_case_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('follow_up', 'Follow Up'),
                    ('complaint', 'Complaint'),
                    ('warranty', 'Warranty'),
                    ('revisit', 'Revisit'),
                    ('feedback', 'Feedback'),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='follow_up_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='follow_up_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='follow_up_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='follow_up_summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
