# Generated by Django 4.2.29 on 2026-04-01 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0012_aftersalescase_creation_source_and_checklist_handoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCrewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.CASCADE, related_name='crew_ticket_assignments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='services.serviceticket')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='ticketcrewassignment',
            constraint=models.UniqueConstraint(fields=('ticket', 'technician'), name='unique_ticket_crew_assignment'),
        ),
    ]
