# Generated by Django 4.2.29 on 2026-04-14 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0013_ticketcrewassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='completion_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='completion_proof_images',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs uploaded as proof of job completion'),
        ),
        migrations.AlterUniqueTogether(
            name='technicianskill',
            unique_together={('technician', 'service_type')},
        ),
    ]
