# Generated by Django 4.2.29 on 2026-04-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_serviceticket_completion_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-request_date']},
        ),
        migrations.AlterModelOptions(
            name='serviceticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['client_id', 'status'], name='services_se_client__2c6fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'request_date'], name='services_se_status_1c7dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['status', 'scheduled_date'], name='services_se_status_08448c_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['technician_id', 'status'], name='services_se_technic_7329e3_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['status', 'created_at'], name='services_se_status_51ab19_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['auto_assigned', 'assigned_at'], name='services_se_auto_as_db7434_idx'),
        ),
    ]
