# Generated by Django 6.0.3 on 2026-03-20 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('services', '0011_inspectionchecklist_proof_media_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTypeInventoryRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('auto_reserve', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_type_requirements', to='inventory.inventoryitem')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_requirements', to='services.servicetype')),
            ],
            options={
                'ordering': ['service_type__name', 'item__name'],
                'unique_together': {('service_type', 'item')},
            },
        ),
    ]
