"""
Django settings for afn_service_management project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import logging
import sys
from pathlib import Path
from dotenv import load_dotenv

_settings_logger = logging.getLogger(__name__)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(BASE_DIR.parent / '.env')


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None or value == '':
        return default
    return value.lower() in ('true', '1', 'yes', 'on')


def env_list(name, default=''):
    value = os.environ.get(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]

# SECURITY WARNING: don't run with debug turned on in production!
ENVIRONMENT = os.environ.get('DJANGO_ENV', 'development').lower()
IS_PRODUCTION = ENVIRONMENT == 'production'
DEBUG = env_bool('DEBUG', default=ENVIRONMENT == 'development')
IS_TEST = 'test' in sys.argv

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # Generate a temporary key for development only
        import secrets
        SECRET_KEY = secrets.token_urlsafe(50)
    else:
        raise ValueError('SECRET_KEY environment variable must be set in production')

DEFAULT_ALLOWED_HOSTS = 'localhost,127.0.0.1,testserver' if DEBUG else ''
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', DEFAULT_ALLOWED_HOSTS)

# OpenRouteService API key support (for route geometry and ETA)
OPENROUTESERVICE_API_KEY = os.environ.get('OPENROUTESERVICE_API_KEY', '').strip()
ORS_API_KEY = os.environ.get('ORS_API_KEY', OPENROUTESERVICE_API_KEY).strip()

# Firebase Cloud Messaging settings
FIREBASE_PROJECT_ID = os.environ.get('FIREBASE_PROJECT_ID', '')
FIREBASE_PRIVATE_KEY_ID = os.environ.get('FIREBASE_PRIVATE_KEY_ID', '')
FIREBASE_PRIVATE_KEY = os.environ.get('FIREBASE_PRIVATE_KEY', '')
FIREBASE_CLIENT_EMAIL = os.environ.get('FIREBASE_CLIENT_EMAIL', '')
FIREBASE_CLIENT_ID = os.environ.get('FIREBASE_CLIENT_ID', '')
FIREBASE_AUTH_URI = os.environ.get('FIREBASE_AUTH_URI', 'https://accounts.google.com/o/oauth2/auth')
FIREBASE_TOKEN_URI = os.environ.get('FIREBASE_TOKEN_URI', 'https://oauth2.googleapis.com/token')
FIREBASE_AUTH_PROVIDER_X509_CERT_URL = os.environ.get('FIREBASE_AUTH_PROVIDER_X509_CERT_URL', 'https://www.googleapis.com/oauth2/v1/certs')
FIREBASE_CLIENT_X509_CERT_URL = os.environ.get('FIREBASE_CLIENT_X509_CERT_URL', '')

# Twilio SMS settings (deprecated - using Firebase instead)
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER', '')

# Security Settings
ENABLE_HTTPS = env_bool('ENABLE_HTTPS', default=IS_PRODUCTION and not IS_TEST)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', default=ENABLE_HTTPS)
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', default=ENABLE_HTTPS)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', default=ENABLE_HTTPS)
USE_X_FORWARDED_HOST = env_bool('USE_X_FORWARDED_HOST', default=IS_PRODUCTION)
SECURE_PROXY_SSL_HEADER = (
    ('HTTP_X_FORWARDED_PROTO', 'https')
    if env_bool('USE_X_FORWARDED_PROTO', default=IS_PRODUCTION)
    else None
)
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000' if SECURE_SSL_REDIRECT else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=SECURE_SSL_REDIRECT)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', default=False)

# Rate limiting (basic - install django-ratelimit for advanced)
# LOGIN_URL removed - using API authentication instead of template auth
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Application definition

INSTALLED_APPS = [
    # Daphne must be first (before staticfiles)
    'daphne',
    
    # Django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'channels',

    # Custom apps
    'users',
    'services',
    # 'progress',  # Temporarily disabled
    'messages_app',  # RE-ENABLED for ClientMessages
    'notifications',  # Re-enabled
    # 'history',  # Temporarily disabled
    # 'forecast',  # Temporarily disabled
    'inventory',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'afn_service_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'afn_service_management.wsgi.application'

# ASGI application for Channels
# ASGI_APPLICATION = 'afn_service_management.asgi.application'

# Channel layers for WebSocket support (use in-memory for development)
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer',
#     },
# }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database configuration with environment variable support
DATABASE_ENGINE = os.environ.get('DATABASE_ENGINE', 'sqlite3').lower()

if DATABASE_ENGINE == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'afn_service_db'),
            'USER': os.environ.get('DB_USER', 'afn_user'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'your_secure_password'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'OPTIONS': {
                # Connection timeout and other PostgreSQL specific options
                'connect_timeout': 10,
            },
            'CONN_MAX_AGE': 60,  # Connection pooling
        }
    }
    _settings_logger.info("Using PostgreSQL database")
elif DATABASE_ENGINE == 'sqlite3':
    # Default to SQLite for development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / os.environ.get('SQLITE_DB_PATH', 'db.sqlite3'),
        }
    }
    _settings_logger.info("Using SQLite database")
else:
    raise ValueError(f"Unsupported DATABASE_ENGINE: {DATABASE_ENGINE}. Use 'sqlite3' or 'postgresql'")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get('TIME_ZONE', 'Asia/Kolkata')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # include custom static directory
STATIC_ROOT = Path(os.environ.get('STATIC_ROOT', str(BASE_DIR / 'staticfiles')))

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'users.User'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': (
        [
            'rest_framework.renderers.JSONRenderer',
            'rest_framework.renderers.BrowsableAPIRenderer',
        ] if DEBUG else [
            'rest_framework.renderers.JSONRenderer',
        ]
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/minute',
        'password_reset': '5/minute',
    },
}

# CORS settings for React frontend — restrict origins in production!
# CORS_ALLOW_ALL_ORIGINS = False  # Uncomment and set CORS_ALLOWED_ORIGINS in production
DEFAULT_FRONTEND_ORIGINS = (
    'http://localhost:5173,'
    'http://127.0.0.1:5173,'
    'http://localhost:5174,'
    'http://127.0.0.1:5174,'
    'http://localhost:3000,'
    'http://127.0.0.1:3000'
    if DEBUG else ''
)
CORS_ALLOW_ALL_ORIGINS = env_bool('CORS_ALLOW_ALL_ORIGINS', default=False)
CORS_ALLOWED_ORIGINS = env_list('CORS_ALLOWED_ORIGINS', DEFAULT_FRONTEND_ORIGINS)
CORS_ALLOWED_ORIGIN_REGEXES = (
    [
        r"^http://localhost:\d+$",
        r"^http://127\.0\.0\.1:\d+$",
    ] if DEBUG else []
)
CORS_ALLOW_CREDENTIALS = env_bool('CORS_ALLOW_CREDENTIALS', default=True)
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS', DEFAULT_FRONTEND_ORIGINS)
FRONTEND_BASE_URL = os.environ.get('FRONTEND_BASE_URL') or (
    CORS_ALLOWED_ORIGINS[0] if CORS_ALLOWED_ORIGINS else 'http://localhost:5173'
)

# Email settings (configure for your email provider)
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = 'AFN Service <noreply@afnservice.com>'

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# API Keys and Free External Services Configuration
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY')

OPENWEATHER_API_KEY = os.environ.get('OPENWEATHER_API_KEY')  # optional free service
FIREBASE_SERVER_KEY = os.environ.get('FIREBASE_SERVER_KEY')  # optional free service


# Admin phone numbers for SMS alerts (comma-separated)
ADMIN_PHONE_NUMBERS = os.environ.get('ADMIN_PHONE_NUMBERS', '').split(',') if os.environ.get('ADMIN_PHONE_NUMBERS') else []

# Email settings from environment
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# Django Channels configuration for WebSocket support
ASGI_APPLICATION = 'afn_service_management.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],
            'capacity': 10000,
            'expiry': 10 * 60,
        },
    }
}

# Fallback to in-memory layer if Redis is unavailable (development only)
if not os.environ.get('USE_REDIS', '').lower() in ('true', '1', 'yes'):
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }
