# Generated by Django 6.0.3 on 2026-03-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_current_latitude_user_current_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_scope',
            field=models.CharField(blank=True, choices=[('after_sales', 'After Sales Management'), ('task_management', 'Task Management'), ('operations', 'Operations Management'), ('general', 'General Administration')], default='general', max_length=50, null=True),
        ),
    ]
