# Generated by Django 4.2.29 on 2026-03-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_admin_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('after_sales', 'After Sales'), ('supervisor', 'Supervisor'), ('technician', 'Technician'), ('client', 'Client')], default='client', max_length=20),
        ),
    ]
