# Generated by Django 4.2.29 on 2026-03-19 10:18

from django.db import migrations, models


def rename_after_sales_role(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(role='after_sales').update(role='follow_up')
    User.objects.filter(admin_scope='after_sales').update(admin_scope='service_follow_up')


def rename_follow_up_role_back(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(role='follow_up').update(role='after_sales')
    User.objects.filter(admin_scope='service_follow_up').update(admin_scope='after_sales')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_scope',
            field=models.CharField(blank=True, choices=[('service_follow_up', 'Service Follow-Up'), ('task_management', 'Task Management'), ('operations', 'Operations Management'), ('general', 'General Administration')], default='general', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('follow_up', 'Service Follow-Up'), ('supervisor', 'Supervisor'), ('technician', 'Technician'), ('client', 'Client')], default='client', max_length=20),
        ),
        migrations.RunPython(rename_after_sales_role, rename_follow_up_role_back),
    ]
